### ISSUE TITLE
[Bug]: Upgraded to HA 2026.5.0 and getting errors from Solid Modbus. Unable to import component: cannot import name 'is_number' from 'homeassistant.helpers.template' (Refuses to start)

### ISSUE THREAD

**Issue by veletron2** [Pho3niX90/solis_modbus#384]
## 🐛 Bug Description
Updated my docker image for HA to latest 2026.5.0, and now seeing errors from Solis.Modbus. This is refusing to start generating an error and a warning in the logs

## 🔄 To Reproduce
1. **Go to**: Update to latest 2026.5.0 via docker integration fails to load afterwards

Have tried updating the integration to latest and restarting everything including the dongle to no avail.

I think this is the main issue: 

Setup failed for custom integration 'solis_modbus': Unable to import component: cannot import name 'is_number' from 'homeassistant.helpers.template' Full details of the error at end...

## ✅ Expected Behavior
Should work with HA Core version 2026.5.0

## 📸 Screenshots / Logs
If applicable, add screenshots or logs to help explain your problem.
- **Home Assistant logs** (filtered to relevant errors)

### 🔹 Home Assistant:
- **Version**: Core-2026-5-0
- **Installation Method**: Docker

### 🔹 Integration:
- **Plugin Version**: Version 4.1.2
- **Device Model**: Solis 5G 3.6kW
- **Modbus Connection Type?**: Ethernet to Solis Dongle
- **Custom Config Entries?**: No

## ➕ Additional Context

**The Error Logged thus:**

```

Logger: homeassistant.setup
Source: setup.py:343
First occurred: 18:13:23 (1 occurrence)
Last logged: 18:13:23

Setup failed for custom integration 'solis_modbus': Unable to import component: cannot import name 'is_number' from 'homeassistant.helpers.template' (/usr/src/homeassistant/homeassistant/helpers/template/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1024, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 86, in run
    result = ctx.run(self.task)
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 73, in run
    return fn(*args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1084, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1398, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/config/custom_components/solis_modbus/__init__.py", line 34, in <module>
    from .data_retrieval import DataRetrieval
  File "/config/custom_components/solis_modbus/data_retrieval.py", line 18, in <module>
    from .modbus_controller import RECOVERABLE_REGISTER_READ_EXCEPTIONS, ModbusController
  File "/config/custom_components/solis_modbus/modbus_controller.py", line 6, in <module>
    from homeassistant.helpers.template import is_number
ImportError: cannot import name 'is_number' from 'homeassistant.helpers.template' (/usr/src/homeassistant/homeassistant/helpers/template/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 343, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1044, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1036, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1084, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1398, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/config/custom_components/solis_modbus/__init__.py", line 34, in <module>
    from .data_retrieval import DataRetrieval
  File "/config/custom_components/solis_modbus/data_retrieval.py", line 18, in <module>
    from .modbus_controller import RECOVERABLE_REGISTER_READ_EXCEPTIONS, ModbusController
  File "/config/custom_components/solis_modbus/modbus_controller.py", line 6, in <module>


    from homeassistant.helpers.template import is_number
ImportError: cannot import name 'is_number' from 'homeassistant.helpers.template' (/usr/src/homeassistant/homeassistant/helpers/template/__init__.py)

```

**Warning Logged is Thus**

```

Logger: homeassistant.util.loop
Source: util/loop.py:77
First occurred: 18:13:23 (1 occurrence)
Last logged: 18:13:23

Detected blocking call to import_module with args ('custom_components.solis_modbus',) in /usr/src/homeassistant/homeassistant/loader.py, line 1084: ComponentProtocol, importlib.import_module(self.pkg_path) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 229, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 215, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 289, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.14/asyncio/base_events.py", line 706, in run_until_complete self.run_forever() File "/usr/local/lib/python3.14/asyncio/base_events.py", line 677, in run_forever self._run_once() File "/usr/local/lib/python3.14/asyncio/base_events.py", line 2046, in _run_once handle._run() File "/usr/local/lib/python3.14/asyncio/events.py", line 94, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 170, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 343, in _async_setup_component component = await integration.async_get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1036, in async_get_component comp = self._get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1084, in _get_component ComponentProtocol, importlib.import_module(self.pkg_path)

```

**Comment by uppaljs** [comment]
+1 , SOLIS S6-12KW inverter, same problem after latest HA update.

**Comment by veletron2** [comment]
I have rolled HA Core back to 2026.4.4 and all working again. Looking at the HA Core Github discussions on 2026.5.0 a number of things have broken. I usually check how long the image has been live before firing off a docker pull for HA with the 'stable' tag, but forgot this time, 2026.5.0 only got the  'stable' tag 2 hours ago!

Guineapig !!!

**Comment by svincetic** [comment]
The integration crashes before it even starts.
The error is here:
from homeassistant.helpers.template import is_numberImportError: cannot import name 'is_number'
This means the solis_modbus custom integration is using an old Python import line that no longer works in your version of Home Assistant. is_number is still a known Home Assistant template function, but this custom integration is trying to import it from a location where it is no longer available.
Fastest fix
Open this file:
/config/custom_components/solis_modbus/modbus_controller.py
At the beginning of the file, find this line:
from homeassistant.helpers.template import is_number
Replace it with this:
import mathdef is_number(value):    try:        return math.isfinite(float(value))    except (TypeError, ValueError):        return False
Then restart Home Assistant.

Help from ChatGPT works for me

**Comment by Arild11** [comment]
> The integration crashes before it even starts. The error is here: from homeassistant.helpers.template import is_numberImportError: cannot import name 'is_number' This means the solis_modbus custom integration is using an old Python import line that no longer works in your version of Home Assistant. is_number is still a known Home Assistant template function, but this custom integration is trying to import it from a location where it is no longer available. Fastest fix Open this file: /config/custom_components/solis_modbus/modbus_controller.py At the beginning of the file, find this line: from homeassistant.helpers.template import is_number Replace it with this: import mathdef is_number(value): try: return math.isfinite(float(value)) except (TypeError, ValueError): return False Then restart Home Assistant.
> 
> Help from ChatGPT works for me

^this worked for me. Thanks for sharing.

**Comment by ElGringo33** [comment]
I can confirm the workaround also needs to be applied in a second file.

After fixing:

/config/custom_components/solis_modbus/modbus_controller.py

Home Assistant still failed with:

ImportError: cannot import name 'is_number' from 'homeassistant.helpers.template'

coming from:

/config/custom_components/solis_modbus/sensors/solis_number_sensor.py

So the same change must also be applied there.

Replace:

from homeassistant.helpers.template import is_number

with:

import math

def is_number(value):
    try:
        return math.isfinite(float(value))
    except (TypeError, ValueError):
        return False

After updating both files and restarting Home Assistant, the integration works again on HA 2026.5.x.

**Comment by Arild11** [comment]
Good catch and i can confirm your confirmation :)
Two files needs to be replaced with the new code.

**Comment by steve-daedilus** [comment]
Great job finding this so quickly and getting an answer. I can confirm I also had the issue.

For clarity for those following me in needing to resolve this, the indentation is important, and this is exactly what worked for me:

in both of these files:
/config/custom_components/solis_modbus/modbus_controller.py
/config/custom_components/solis_modbus/sensors/solis_number_sensor.py

Replace the line:

`from homeassistant.helpers.template import is_number`


With the following code:

```
def is_number(value):
    try:
        return math.isfinite(float(value))
    except (TypeError, ValueError):
        return False
```

**Comment by steve-daedilus** [comment]
Sorry for the rubbish formatting. Can't find a way to have the comments present code indentation.

**Comment by ElGringo33** [comment]
Same here 😄
I couldn't find a proper way to preserve indentation in GitHub comments either.

**Comment by veletron2** [comment]
I thought the tripple back tick  (upper left on UK keyboard) on a line of its own either end of code block would do this? See screenshot!

<img width="1200" height="1108" alt="Image" src="https://github.com/user-attachments/assets/09f97d3f-932b-4ab7-88af-3adf30675733" />

```
def is_number(value):
   try:
      return math.isfinite(float(value))
   except (TypeError, ValueError):
      return False
```

NB im on a phone. Not ideal!

**Comment by steve-daedilus** [comment]
I should have known that... I only do exactly that on Discord! Doh!

**Comment by Nicopri** [comment]
Hello team, just a big shout-out to you. I tried rolling back everything, but nothing worked until I found this thread. Thanks a lot for the quick patch, you rock!

**Comment by IanPHeitmans** [comment]
Thanks for the help that fixed this so quickly. Hopefully this will soon be integrated into a new official version.

**Comment by charliegadget** [comment]
This is the same issue reported in #386. A fix is ready and awaiting maintainer approval in PR #387.

The PR replaces the removed `is_number` import from `homeassistant.helpers.template` with a local equivalent, and also fixes two other HA 2026.5 breaking API changes (`OptionsFlowWithConfigEntry` removed, `hass.components.persistent_notification` removed). All CI checks pass.

In the meantime, if you need a working fix now, you can manually apply the changes from the PR to your local installation.

**Comment by Pho3niX90** [comment]
Fixed in #387
